logging:
  level:
    root: INFO

server:
  tomcat.uri-encoding: UTF-8
  port: 9999
  sessionTimeout: 30

spring:
  datasource:
    url: jdbc:mysql://139.196.52.84:3306/waterpro?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 122333444455555
    driverClassName: com.mysql.jdbc.Driver

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
